export interface Clientes {
  idCliente:number,
  idVendedor:number,
  createDate:Date,
  nombre:string,
  calle:string,
  numExt:string,
  numInt:string,
  entreCalles:string,
  codigocolonia:number,
  razonSocial:string,
  rfc:string,
  telefono:string,
  email:string,
  lat:string,
  long:string,
  active:boolean,
  bCredito:boolean,
  iDiasCredito:string,
  limiteCredito:string,
  idTipoCliente:number,
  bPuntoDVenta:boolean,
  bDineroElectronico:boolean,
  idZona:number,
  bProspecto:boolean,
  bFProspecto:boolean,
  compraEstimada: number,
  idGiro?: number
 }

 export function initClientes(): Clientes{
    return {
        idCliente: 0,
        idVendedor: 0,
        createDate: new Date(),
        nombre: '',
        calle: '',
        numExt: '',
        numInt: '',
        entreCalles: '',
        codigocolonia: 0,
        razonSocial: '',
        rfc: '',
        telefono: '',
        email: '',
        lat: '',
        long: '',
        active: true,
        bCredito: false,
        iDiasCredito: '',
        limiteCredito: '',
        idTipoCliente: 0,
        bPuntoDVenta: false,
        bDineroElectronico: false,
        idZona: 0,
        bProspecto: false,
        bFProspecto: false,
        compraEstimada: 0,
        idGiro: 0
    };
 }
